### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by mfloto** [plantineers/plantbuddy-server#31]
_Proposal:_

`/user/{USER_NAME}` endpoint:
- [x] `GET` return the user if the request is authenticated by that user
- [x] `DELETE` delete user (only for users with the role `admin` ) 
- [x] `POST` create user (only for users with the role `admin` )
- [x] `PUT` change user (only for users with the role `admin` )

`/users` endpoint:
- [x] `GET` returns an array containing all users (only for users with the role `admin` )

_Alternative: The frontend makes a GET request to `/login`. This endpoint would behave like `/user`._

user-object:
- ID (generated by SQLite)
- NAME
- PASSWORD
- ROLE

User authentication:
- simplest: Include headers with username and password in every request (`X-User-Name`, `X-User-Password`); use middleware to check those headers on every request
- more sophisticated: Generate token (jwt?) that needs to be included with every request; check token with middleware

- [ ] Update api.yml

**Comment by Flippchen** [comment]
Sounds good. The simple authentication should be enough. But maybe we should really encrypt all requests in general if we send username/password with every request

**Comment by mfloto** [comment]
> Sounds good. The simple authentication should be enough. But maybe we should really encrypt all requests in general if we send username/password with every request

Ideally, all of the traffic is encrypted. Otherwise, the `jwt` variant is also flawed.
