### ISSUE TITLE
Edit plant datastructure

### ISSUE THREAD

**Issue by mfloto** [plantineers/plantbuddy-server#35]
_Proposal:_
New fields for plant:
- `name` - String
- `species` - String
- `location` - String

Add endpoints:
- `POST` - Create plant
- `DELETE` - Delete plant

Modify `/plants` endpoint:
- query via parameters: name, species, location

Stakeholder: @MarionHinkel @Flippchen

**Comment by MarionHinkel** [comment]
Did you add name already? 
But good recommendations!

**Comment by mfloto** [comment]
Not yet, but I added the name field to the proposal
