### ISSUE TITLE
Handle plant-group and plant relation

### ISSUE THREAD

**Issue by mfloto** [plantineers/plantbuddy-server#68]
The following cases need to be handled:
- [x] plant is created with non-existing plant-group-id -> Return 400? ("plantGroup does not exist")
- [x] plant-group is deleted but there are still plants using this plant-group-id -> Return 400? ("only empty plantGroups can be deleted")

**Comment by yannickkirschen** [comment]
Yeah, good idea! In case of a deletion, the database should trigger a cascade deletion, but this is not sure. We should either return an error when it is still in use or delete all plants recursively.

**Comment by yannickkirschen** [comment]
I just discovered, that SQLite allows the insertion of a plant with a non-existing plant-group although it is defined as a foreign key. "Normal" databases won't allow this but we have to cover this case. Sad ...
